<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>2.6.4</Version>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>..\..\installer\assets\Sentinel.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sentinel.Core\Sentinel.Core.csproj" />
  </ItemGroup>

</Project>
